### ISSUE TITLE
PLAYER.svg failed to load in linux

### ISSUE THREAD

**Issue by MarcBoule** [cfoulc/cf#1]
As mentionned in FB, the files are case sensitive in linux, so either the file should become: "PLAYER.svg" as opposed to "player.svg", or change the code to call "player.svg" instead of "PLAYER.svg".

**Comment by cfoulc** [comment]
thanks, it'll be done :)

**Comment by cfoulc** [comment]
done

**Comment by MarcBoule** [comment]
Super, confirmed everything work, thank you very much!
