### ISSUE TITLE
compile error with new includes for PLAYER

### ISSUE THREAD

**Issue by phdsg** [cfoulc/cf#10]
```
src/PLAYER.cpp:7:10: fatal error: sys/dir.h: No such file or directory
 #include <sys/dir.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [../../compile.mk:54: build/src/PLAYER.cpp.o] Error 1

```
what's that include? maybe i can find the correct one for windows.

**Comment by phdsg** [comment]
okay. it's just <dir.h> in my mingw64

**Comment by cfoulc** [comment]
thx i'll try to get a solution to this

**Comment by dBiz** [comment]
Compiled on windows modifying 
#include <dir.h>, hope it helps ;)

**Comment by cfoulc** [comment]
thx also, it seems only "#include <dirent.h>"  is needed, so i took off dir.h and sys stuff : 
//#include <sys/dir.h>
#include <dirent.h>
//#ifndef WIN32
//    #include <sys/types.h>
//#endif
i think/hope dirent.h is common to all systems.
i still need to find solutions for end and beginning of folder and for not supported files while browsing. :)
