### ISSUE TITLE
Suggestion: Input modulation

### ISSUE THREAD

**Issue by Coirt** [cfoulc/cf#15]
Recently seen how the knobs on Mono/Stereo and other cf modules respond to a mod source by animating their progression this is fantastic and should be a feature in all of rack. What would make this even better would be if the knob remembers the state on a disconnect. Connect midi to the knob and set it from your midi controller when you disconnect that cable it remembers the position making the fader/knob on you midi available for something else.

**Comment by cfoulc** [comment]
not easily done, but i'm still trying :)
