### ISSUE TITLE
one typo that prevents building with 0.6

### ISSUE THREAD

**Issue by Chaircrusher** [cfoulc/cf#18]
One change got things building...
diff --git a/src/PLAYER.cpp b/src/PLAYER.cpp
index 8aada0b..1cdb499 100644
--- a/src/PLAYER.cpp
+++ b/src/PLAYER.cpp
@@ -1,6 +1,6 @@
 #include "cf.hpp"
 #include "dsp/digital.hpp"
-#include "../ext/osdialog/osdialog.h"
+#include "../dep/osdialog/osdialog.h"
 #include "AudioFile.h"
 #include <vector>
 #include "cmath"

**Comment by cfoulc** [comment]
you're right, it did work and it doesn't any more so i'm changing it :) 
(i just managed to get a newer 060dev)
thanx
