### ISSUE TITLE
any plans of updating for version one?

### ISSUE THREAD

**Issue by LeonFedotov** [cfoulc/cf#32]
hello, i would love seeing this module updated for version one of rack? :)

**Comment by ROGAVKA** [comment]
heavy plus sign. i just can't imagine my workflow without your mixer :( if you don't plan an update, how would you feel about someone else porting these?

**Comment by hexdump0815** [comment]
another plus for this from here :)

**Comment by Brennan-VanderLaan** [comment]
I too would love to know, not having your modules in 1.0 made me realize how much I rely on them :D

**Comment by nay-seven** [comment]
Check releases ?  ;-)

https://github.com/cfoulc/cf/releases/tag/1.0.1?fbclid=IwAR24e2kdaenZvbK78uZNXRFOo59WuBeqcZMVHGJBg8Ov-Zy8NDi01VRL8DA

**Comment by Brennan-VanderLaan** [comment]
Oh wow, that timing. Thanks @nay-seven! And you rock @cfoulc  :D

**Comment by LeonFedotov** [comment]
WOOO !
