### ISSUE TITLE
LBL crashes on Windows 10

### ISSUE THREAD

**Issue by Ahornberg** [cfoulc/cf#35]
LBL crashes on Windows 10 after clicking on "Enter label" in the context-menu

[6.362 fatal src/main.cpp:45] Fatal signal 22. Stack trace:
21: ZN4rack10appDestroyEv 0x456435
20: raise 0x4044ac60
19: abort 0x4044f270
18: assert 0x4044b510
17: osdialog_prompt 0x4a9292
16: ZN9LABELItem8onActionERKN4rack5event6ActionE 0xd45c5a0
15: ZN4rack2ui8MenuItem8doActionEv 0x4a49ae
14: ZN4rack5event5State12handleButtonENS_4math3VecEiii 0x4576c8
13: ZN4rack7updater17isUpdateAvailableEv 0x45914e
12: glfwPlatformUnlockMutex 0x4d78ae
11: CallWindowProcW 0x406c6030
10: CallWindowProcW 0x406c6030
9: glPushClientAttrib 0x20913770
8: CallWindowProcW 0x406c6030
7: DispatchMessageW 0x406c5bf0
6: glfwPlatformPollEvents 0x4daf66
5: ZN4rack6Window3runEv 0x4594ea
4: main 0x781840
3: main 0x781840
2: main 0x781840
1: BaseThreadInitThunk 0x3f737bc0
0: RtlUserThreadStart 0x4162ceb0

**Comment by ShockValu3** [comment]
Same experience here.
Attaching log and screenshot

![crash](https://user-images.githubusercontent.com/62047366/76384576-9350c680-631c-11ea-9148-c417f262e73e.png)


[log.txt](https://github.com/cfoulc/cf/files/4316142/log.txt)

**Comment by scheichreisuli** [comment]
Same issue here (Ryzen-system). AfaIk there is no alternative module, would be very nice to fix it.

**Comment by SaccoSVD** [comment]
Same here. 3900X

**Comment by krzysztofKKW** [comment]
Same here

**Comment by awebneck** [comment]
I love the aesthetics of this module, but yeah, this is definitely happening. @scheichreisuli one alternative is Submarine's TD-202: https://library.vcvrack.com/SubmarineFree/TD-202. I don't like the look of that one as much as I do LBL, but it does the job in the meantime (and I also don't know how I ever lived without some of Submarine's other modules, so it's a worthwhile collection to grab even outside the LBL clone)

**Comment by nmall** [comment]
Looks like it's still an issue for me too.

**Comment by cxbignekoc** [comment]
exact same "cryptic" message...i kill my request issue then...
